#!/usr/bin/env bash
# by Ereptor, TurtleCoin

HASH=$1
# 2aca6643bb4fbd21b19e8828fcedf5b3b1f77be099850a3e3dec288b029496b5

curl --silent 'https://explorer.kryptonchain.org/node-api/json_rpc' --data '{"jsonrpc":"2.0","id":"test","method":"f_transaction_json","params":{"hash":"'"$HASH"'"}}' --compressed | jq '.result.tx.extra' | xxd -r -p













